version: '3.8'
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        - VITE_REVERB_APP_KEY
        - VITE_REVERB_HOST
        - VITE_REVERB_PORT
        - VITE_REVERB_SCHEME
        - VITE_REVERB_CLUSTER
    container_name: meu-vue-app
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
