server {
  listen 80;
  server_name gestao.controleobras.online;

  root /usr/share/nginx/html;
  index index.html;

  # Redireciona todas as rotas para index.html, necessário para SPAs
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Opcional: define o fallback de erro 404 para index.html
  error_page 404 /index.html;

  # Cache e headers opcionais (melhora performance)
  location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
    expires 1y;
    access_log off;
    add_header Cache-Control "public";
  }
}
